version: '3.8'

services:
  ranking:
    build: .
    container_name: ranking-operadores
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ranking-data:/app/data
    environment:
      - PORT=3000
      - ADMIN_USER=admin
<<<<<<< HEAD
      - ADMIN_PASS=meta2025
=======
      - ADMIN_PASS=U2nhhOJjtdCEyn
>>>>>>> feebf4eb2947bdaa43d1d108edce3636f9bf6cb6
      - SESSION_SECRET=troque-esta-chave-secreta-agora
    labels:
      - "com.centurion.description=Ranking Operadores Dashboard"

volumes:
  ranking-data:
    driver: local
